### ISSUE TITLE
Apakah ada cara untuk menerjemahkan ini ke dalam bahasa Inggris? Is there away to translate this into english?

### ISSUE THREAD

**Issue by Erik-Da-coder** [ChromaMinecraft/chroma-minecraft-frontend#31]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Can you put a version where the language is english? Bisakah Anda memasukkan versi yang bahasanya bahasa Inggris?
**Describe alternatives you've considered**
NON
**Additional context**

**Comment by Aldiwildan77** [comment]
Hi, I thought that you could fork this repository and convert it to your use case because we already deprecated it
